import React from 'react';
import Head from 'next/head';

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }) => (
  <>
    <Head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      {/* Other meta tags can be added here */}
    </Head>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  </>
);

export default Layout;
