// components/Layout.js
import React from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import Info from '../components/InformationSection'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href={inter.href} />
      </Head>
      <body className={inter.className}>
        <Navbar />
        <Hero />
        <Info />
        {children}
      </body>
    </html>
  );
}
